name: Tag-Build-Push

on:
  workflow_dispatch:
    inputs:
      newTag:
        description: "New tag"
        required: true
        default: "x.x.x"
      tbumpOption:
        description: "tbump option (to run, use: `--non-interactive`"
        default: "--dry-run"

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip3 install --upgrade setuptools
          pip3 install wheel tbump
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Configure git
        run: |
          git config --global user.email "joe@ordisius.com"
          git config --global user.name "joe"

      - name: tbump dry-run
        if: ${{ github.event.inputs.tbumpOption }} == '--dry-run'
        run: |
          tbump ${{ github.event.inputs.tbumpOption }} ${{ github.event.inputs.newTag }}

      - name: tbump run
        if: ${{ github.event.inputs.tbumpOption }} == '--dry-run'
        run: |
          tbump ${{ github.event.inputs.tbumpOption }} ${{ github.event.inputs.newTag }}

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      if: ${{ github.event.inputs.tbumpOption }} == '--non-interactive'
      uses: actions/checkout@v2

    - name: Login to GitHub Package Registry
      if: ${{ github.event.inputs.tbumpOption }} == '--non-interactive'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build the docker image
      if: ${{ github.event.inputs.tbumpOption }} == '--non-interactive'
      run: docker build . --file Dockerfile --tag ghcr.io/jperez3/hive:${{ github.event.inputs.newTag }} --tag ghcr.io/jperez3/hive:${{ github.sha }}

    - name: Push docker image to github container registry
      if: ${{ github.event.inputs.tbumpOption }} == '--non-interactive'
      run: docker push ghcr.io/jperez3/hive:${{ github.event.inputs.newTag }}
