name: Tag Creation

on:
  workflow_dispatch:
    inputs:
      newTag:
        description: "New tag"
        required: true
        default: "x.x.x"
      tbumpOption:
        description: "tbump option (to run, use: `--non-interactive`"
        default: "--dry-run"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip3 install --upgrade setuptools
          pip3 install wheel tbump
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tbump
        run: |
          tbump ${{ github.event.inputs.tbumpOption }} ${{ github.event.inputs.newTag }}
