on:
    workflow_dispatch:
      inputs:
        newTag:
          description: 'New tag'
          required: true
          default: 'warning'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name:
      run: |
        echo "New Tag: ${{ github.event.inputs.newTag }}"
    - name: Install tbump
      run: pip3 install tbump
    - name: tbump dry-run
      run: tbump --dry-run ${{ github.event.inputs.newTag }}
