name: Tag Creation

on:
  workflow_dispatch:
    inputs:
      newTag:
        description: "New tag"
        required: true
        default: "x.x.x"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install tbump
        run: |
          pip3 install --upgrade setuptools
          pip3 install wheel
          pip3 install tbump
      - uses: actions/checkout@v2
      # - name: Install prereqs
      #   run: pip3 install --upgrade setuptools && pip3 install wheel
      # - name: Install tbump
      #   run: pip3 install tbump



      - name: tbump dry-run
        run: sleep 15 && tbump --dry-run ${{ github.event.inputs.newTag }}
